### PR TITLE
Make loop for `smallest_dimension_yet` inclusive

### LINKED ISSUE #11: Bug in smallest_diminesions_yet calculation?
I believe this for loop code
https://github.com/ogham/rust-term-grid/blob/99396dd62e2a683ce4ddb1f6ce46612c4eabc3d7/src/lib.rs#L383

should be inclusive
```rust
for num_lines in (1..=theoretical_max_num_lines).rev() {
```
I ran into this problem where the output should've been 2 rows but it would never output 2 rows. It would always fail and return the initialized value of `None` for `smallest_dimensions_yet`.

Please confirm.

Thanks!

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Closes https://github.com/ogham/rust-term-grid/issues/11

Hi! Thanks for this great library! Like I mentioned in the issue, we would love to upgrade to a later version, but this is blocking us, so I thought I would implement it in a PR. It contains exactly the change in the issue.

### CODE REVIEW

**Comment by mtsoltan** [comment]
This is necessary, please merge it.

**Comment by sylvestre** [comment]
@ogham
would you be ok to merge it? thanks

**Comment by sylvestre** [comment]
@behnam @ogham seems to be MIA. Is that something you could help with? thanks

**Comment by tertsdiepraam** [comment]
`uutils` and `eza` are both using `uutils-term-grid` now, an actively maintained fork of this library. Many thanks to @ogham for creating an awesome library we can build upon!

**Pull request closed without merging**
